name: SurroundingTeleporter
main: fr.aurelien30000.surroundingteleporter.SurroundingTeleporter
version: ${project.version}
api-version: 1.16
author: Aurelien30000
description: A plugin that teleports surrounding entities with players.

commands:
  surroundingteleporter:
    description: "Main command."
    permission: surroundingteleporter.use
    aliases:
      - sutp

permissions:
  surroundingteleporter.use:
    description: "Permission to execute /surroundingteleporter"
    default: op